#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Start picom
picom &

# Set keyboard layout to gb
setxkbmap gb

# Set background image
feh --bg-center ~/.config/wallpapers/wallpaper.jpg

# Start polybar
lofibarlaunch

# The numbers may be different on other devices
# Natural scrolling on trackpad
xinput --set-prop 13 338 1

# Enable tapping on touchpad
xinput --set-prop 13 315 1

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ksnip state=floating
